#name: CI/CD
#on: push
#
#jobs:
#  run-my-command:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Copy Files
#        run: echo "Some text"
#
#      - uses: actions/checkout@v4 # копируем репозиторий чекаутом
#      - name: List Files
#        run:
#          ls -a
#      - name: Install requirements
#        run: pip install -r requirements.txt  # python -m pip install -r requirements.txt


name: Lint Python Code

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint: # The name of the job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"

