name: Lint Python Code

on: push

jobs:
  run-first-command:
    runs-on: ubuntu-latest
    steps:
      - name: Display some Asd
        run: echo "Some text"
  call-workflow-lint:
    uses: ./.github/workflows/linters.yml
  call-workflow-test:
    uses: ./.github/workflows/tests.yml
