name: Reusable Workflow
on: push

jobs:
  console-log:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: set up python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Get pip cache dir
        run: |
          echo "PIP_CACHE_DIR=$(pip cache dir)" >> $GITHUB_ENV
          echo "PIP_CACHE_KEY=${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}" >> $GITHUB_ENV
  
      - name: Restore pip cache
        uses: actions/cache/restore@v4
        with:
          path: ${{ env.PIP_CACHE_DIR }}
          key: ${{ env.PIP_CACHE_KEY }}
          restore-keys: |
            ${{ runner.os }}-pip-
  
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run flake8
        run: |
          flake8 main1.py     
  
      - name: Save pip cache
        uses: actions/cache/save@v4
        if: always()
        with:
          path: ${{ env.PIP_CACHE_DIR }}
          key: ${{ env.PIP_CACHE_KEY }}


      - name: Run flake8
        run: |
          flake8 main1.py          
